# Generated by Django 3.0.5 on 2020-04-11 02:11

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackTestTryd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('paper', models.CharField(max_length=10)),
                ('opening', models.TimeField()),
                ('closing', models.TimeField()),
                ('time_total', models.TimeField()),
                ('amount', models.IntegerField()),
                ('type_operation', models.CharField(choices=[('C', 'COMPRA'), ('V', 'VENDA')], max_length=1)),
                ('average_price_buy', models.DecimalField(decimal_places=5, max_digits=12)),
                ('average_price_sell', models.DecimalField(decimal_places=5, max_digits=12)),
                ('result_close', models.DecimalField(decimal_places=5, max_digits=12)),
                ('result_open', models.DecimalField(decimal_places=5, max_digits=12)),
                ('result_total', models.DecimalField(decimal_places=5, max_digits=12)),
                ('date_operation', models.DateField()),
                ('cost_operation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tet', models.TimeField()),
                ('mep', models.DecimalField(decimal_places=2, max_digits=12)),
                ('men', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_result', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
